{
 "title": "dashboard-remlateam2",
 "time": { "from": "now", "to": "now" },
 "panels": [
  {
   "title": "Average heart review",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "average_rating{rating=\"hearts\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average star review",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "average_rating{rating=\"stars\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback difference per day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (sum by(le) (feedback_per_day_bucket) unless on(le) feedback_per_day_bucket{le=\"+Inf\"}) unless on(le) feedback_per_day_bucket{le=\"+Inf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The amount of reviews",
   "type": "stat",
   "description": "The amount of reviews",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictions_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accuracy of predictions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Feedback summary sum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "feedback_summary_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}