services:
  model-service:
    image: ghcr.io/remla23-team2/model-service:1.2.0
    volumes:
      - shared-data:/root/data
      - shared-code:/root/src
    ports:
      - 8080:8080
    depends_on:
      - model-training
  model-training:
    image: ghcr.io/remla23-team2/model-training:1.2.0
    volumes:
      - shared-data:/root/data
      - shared-code:/root/src
  app:
    image: ghcr.io/remla23-team2/app:1.2.0
    ports:
      - 3000:3000
    depends_on:
      - model-service
    environment:
      - API_URL=http://model-service:8080

volumes:
  shared-data:
  shared-code:
