services:
  model-service:
    image: ghcr.io/remla23-team2/model-service:2.2.0
    volumes:
      - shared-data:/root/data
      - shared-code:/root/src
    ports:
      - 8080:8080
    depends_on:
      - model-training
  model-training:
    image: ghcr.io/remla23-team2/model-training:1.2.0
    volumes:
      - shared-data:/root/data
      - shared-code:/root/src
  app:
    image: ghcr.io/remla23-team2/app:3.4.5
    ports:
      - 3000:80
    depends_on:
      - gateway
    environment:
      - API_URL=http://gateway:3000
  gateway:
    image: ghcr.io/remla23-team2/gateway:1.1.0
    depends_on:
      - model-service
    environment:
      - MODEL_SERVICE_URL=http://model-service:8080

volumes:
  shared-data:
  shared-code:
