apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-depl
  labels:
    app: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla23-team2/model-service:1.5.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: model-service-serv
  labels:
    app: model-service
spec:
  selector:
    app: model-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/remla23-team2/app:1.5.2
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: model.host
          - name: PUBLIC_URL
            value: "/app"
---
apiVersion: v1
kind: Service
metadata:
  name: app-serv
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: "/app"
        pathType: Prefix
        backend:
          service:
            name: app-serv
            port:
              number: 3000
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: model-service-serv
            port:
              number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  model.host: "http://localhost/"