{
 "title": "dashboard-remlateam2",
 "time": { "from": "now", "to": "now" },
 "panels": [
  {
   "title": "The amount of reviews",
   "type": "stat",
   "description": "The amount of reviews",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictions_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accuracy of the predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Feedback difference per day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (sum by(le) (feedback_per_day_bucket) unless on(le) feedback_per_day_bucket{le=\"+Inf\"}) unless on(le) feedback_per_day_bucket{le=\"+Inf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "day_of_week(sum by(day_of_week) (sum by (day_of_week) (feedback_per_day_bucket) fill(0)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}