apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.yaml: |
    apiVersion: 1
    env:
      GF_SERVER_ROOT_URL: https://localhost:3000/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
    adminPassword: prom-operator
    defaultDashboardsEnabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      path: "/grafana(/|$)(.*)"

