apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: rest
spec:
  selector:
    matchLabels:
      app: {{ .Values.modelService.service.label }}
  endpoints:
  - interval: 1s