apiVersion: v1
kind: Service
metadata:
  name: model-service-serv
  labels:
    app: {{ .Values.modelService.service.label }}
spec:
  selector:
    app: {{ .Values.modelService.deployment.label }}
  ports:
    - name: http-service
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.service.name }}
  labels:
    app: {{ .Values.gateway.service.label }}
spec:
  selector:
    app: {{ .Values.gateway.deployment.label }}
  ports:
    - name: http-service
      port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: app-serv
spec:
  selector:
    app: {{ .Values.app.deployment.label }}
  ports:
    - name: http-app
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}