webapp:
name: webapp
replicas: 1
tag: 2.0.0
port: 3000
service:
  name: webapp-service 

monitoring:
name: monitoring-service-monitor

kube-prometheus-stack: 
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths: ["/prometheus(/|$)(.*)"]

grafana:
  env:
    GF_SERVER_ROOT_URL: https://localhost:80/grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
  # username is 'admin'
  adminPassword: prom-operator
  defaultDashboardsEnabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: "/grafana(/|$)(.*)"